### ISSUE TITLE
UIScrollView disabling timer temporarily

### ISSUE THREAD

**Issue by rodmaz** [rsrbk/SRCountdownTimer#12]
My UI has a WKWebView and whenever the user touches the WKWebView and scrolls the timer stops.
Any idea?

**Comment by rsrbk** [comment]
Hi Rodrigo!
Thank you for the report. Your issue was fixed in the commit 8de785f. The new release will be available within few hours.

https://stackoverflow.com/questions/34234939/swift-nstimer-stop-when-scrolling
