### ISSUE TITLE
How to know when the timer is finished ?

### ISSUE THREAD

**Issue by AntoineWaes** [rsrbk/SRCountdownTimer#13]
Hey
Can you help me figure out when the timer is finished ? 
I see that there is a delegate for that, but I have no idea how to implement that ...
Thanks

**Comment by rsrbk** [comment]
Hello!
Just set your class as a delegate:
`countdownTimer.delegate = self`

And then implement the delegate method in the same class:
`func timerDidEnd() { }`
This one will be called right after the timer is finished.
