### ISSUE TITLE
not work on iOS 9

### ISSUE THREAD

**Issue by resand** [rsrbk/SRCountdownTimer#14]
The start function does not work on iOS 9.
What would be the correct way to make it work in iOS 9 or higher?

![ios9_](https://user-images.githubusercontent.com/5307015/35061230-373e9b60-fb86-11e7-9857-1148068b8115.png)
![ios9](https://user-images.githubusercontent.com/5307015/35061235-3cc2fcb6-fb86-11e7-91d2-7713d8af901d.png)

**Comment by rsrbk** [comment]
Hello! This is solved! The 1.1 version supports iOS 9 so you can safely update :)
