### ISSUE TITLE
App is running in background

### ISSUE THREAD

**Issue by resand** [rsrbk/SRCountdownTimer#17]
Continue countdown timer when app is running in background

**Comment by app-web-dev** [comment]
Having same issue!

**Comment by resand** [comment]
@app-web-dev I solved it with observers!

**Comment by ajeetpratap** [comment]
I am stuck with this same issue.. I want the timer to run even the app goes in background. @resand How you solved it with observer?

**Comment by resand** [comment]
@ajeetpratap Use an observer when sending the app to the background and disable the timer, returning to the foreground subtractthe time difference and initialize the timer again.

```
override func viewDidLoad() {
    super.viewDidLoad()
    NotificationCenter.default.addObserver(self, selector: #selector(willResignActive), name: .UIApplicationWillResignActive, object: nil)
    NotificationCenter.default.addObserver(self, selector: #selector(didBecomeActive), name: .UIApplicationDidBecomeActive, object: nil)
}

@objc func willResignActive(_ notification: Notification) {
     currentBackgroundDate = Date()
     timer.invalidate()
}
    
@objc func didBecomeActive(_ notification: Notification) {
     let calender: Calendar = Calendar.current
     let components: DateComponents = calender.dateComponents([.year, .month, .day, .hour, .minute, .second], from: currentBackgroundDate!, to: Date())
     let seconds = components.second
     let secondsUpdate = countDownView.currentSecond - seconds!
        
     countDownView.start(beginingValue: secondsUpdate, interval: 1)
}
```

**Comment by ajeetpratap** [comment]
@resand Thanks for the quick reply:
`countDownView.start(beginingValue: secondsUpdate, interval: 1)` will start the timer again and it will also update the UI also.I want to persist the UI and resume it again when I come to foreground. 
Any thoughts on that?

**Comment by resand** [comment]
@ajeetpratap You could check if the library has a function to get the time difference and keep the UI. 
He served me as an example.
