### ISSUE TITLE
Getting How much Time is elapsed ?

### ISSUE THREAD

**Issue by kalrashubham49** [rsrbk/SRCountdownTimer#18]
Getting How much Time is elapsed?, when i stop the quiz,want to take note of that as well

**Comment by ionsilviumihai** [comment]
Modify the method called timerDidEnd from the protocol SRCountdownTimerDelegate and send elapsedTime variable as a member
    @objc public protocol SRCountdownTimerDelegate: class {
        @objc optional func timerDidEnd(elapsedTime: TimeInterval)
    }

    /**
     * End the timer
     */
    public func end() {
        self.currentCounterValue = 0
        timer?.invalidate()
        
        delegate?.timerDidEnd?()
    }

**Comment by rsrbk** [comment]
Thanks @ionsilviumihai ! I'll commit it to master.
