### ISSUE TITLE
Circle Not completeing

### ISSUE THREAD

**Issue by MobileMon** [rsrbk/SRCountdownTimer#19]
Circle does not fill the ring in these scenarios

        countdownTimer.start(beginingValue: 2, interval: 1)
or
        countdownTimer.start(beginingValue: 2, interval: 0.2)

**Comment by ionsilviumihai** [comment]
Check this method and try to replace the if verification with if: elapsedTime <= totalTime. There are some cases when it goes to else branch without to have a complete circle.

@objc private func timerFired(_ timer: Timer) {
        elapsedTime += fireInterval

        if elapsedTime < totalTime {
            setNeedsDisplay()

            let computedCounterValue = beginingValue - Int(elapsedTime / interval)
            if computedCounterValue != currentCounterValue {
                currentCounterValue = computedCounterValue
            }
        } else {
            end()
        }
    }

**Comment by rsrbk** [comment]
Thanks @ionsilviumihai ! I'll merge it to master.
