### ISSUE TITLE
Reset Trail Line

### ISSUE THREAD

**Issue by SerhanAksut** [rsrbk/SRCountdownTimer#22]
There is no reset property for circular progressView. How to achieve to reset trail line ?

**Comment by zackb** [comment]
This is not a good solution, but I made `elapsedTime` public and:
```
timerView.delegate = nil
timerView.end()
timerView.elapsedTime = 0
timerView.setNeedsDisplay()
```

**Comment by rsrbk** [comment]
Sounds like a solution. @zackb I would be really glad if you can submit a PR with your solution as another public method `reset()`.

**Comment by zackb** [comment]
@rsrbk here you go! https://github.com/rsrbk/SRCountdownTimer/pull/29

**Comment by rsrbk** [comment]
@zackb so quick! :D merged

**Comment by rsrbk** [comment]
thank you for contributing!
