### ISSUE TITLE
Seriosuly no upgrade for Swift 4.2? 

### ISSUE THREAD

**Issue by krish23** [rsrbk/SRCountdownTimer#30]
I have migrated my project to Swift 4.2. Now your pod is not working.. seriously man you did not upgrade to Swift 4.2?

**Comment by krish23** [comment]
Again Man. Xcode 11 is out and we cannot use Swift 3 anymore. I would say this piece of software is DEAD from this month on wards. The developer is not doing anything. USELESS MAN!!!!!!

**Comment by rsrbk** [comment]
Upgraded to Swift 5. Please let me know if there are still any issues.
Also, you can always contribute to an open source project by yourself instead of waiting for someone to do it.
