### ISSUE TITLE
Timer Label not showing

### ISSUE THREAD

**Issue by NiklasOemler** [rsrbk/SRCountdownTimer#38]
Hi! First of all thanks sharing your pod to the open source community.

I was playing around with some Countdown Pods to integrate one into my app which Is already live in the stores. 

Unfortunately im not able to see the timer label in the circle. Any help would be appreciated.
I can see the Label in the view hierarchy but it has no frame and so its not visible ..
Cheers.

`class CountdownViewController: UIViewController, SRCountdownTimerDelegate {

    private var countdownView: CountdownView {
        return view as! CountdownView
    }

    // MARK: - View Lifecycle
    override func loadView() {
        view = CountdownView()
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        countdownView.countdownTimer.delegate = self
        countdownView.countdownTimer.start(beginingValue: 5, interval: 1)
    }

    // MARK: - SRCountdowntimer Delegate

    func timerDidUpdateCounterValue(sender: SRCountdownTimer, newValue: Int) {
        print(newValue)
    }

    func timerDidStart(sender: SRCountdownTimer) {
        print("Start")
    }

    func timerDidEnd(sender: SRCountdownTimer, elapsedTime: TimeInterval) {
        print("End")
    }
}`

`class CountdownView: UIView {

    public let countdownTimer: SRCountdownTimer = {
        let timer = SRCountdownTimer()
        timer.translatesAutoresizingMaskIntoConstraints = false
        timer.backgroundColor = .white
        timer.lineColor = .systemGreen
        timer.labelTextColor = .black
        timer.isLabelHidden = false
        timer.labelFont = .systemFont(ofSize: 30)
        timer.timerFinishingText = "Finish"
        return timer
    }()

    // MARK: - Object Lifecycle

    override init(frame: CGRect) {
        super.init(frame: frame)

        backgroundColor = .white
        addSubview(countdownTimer)

        setupConstraints()
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) not supported!")
    }

    // MARK: - Layout

    private func setupConstraints() {

        // Timer
        NSLayoutConstraint.activate([countdownTimer.centerYAnchor.constraint(equalTo: centerYAnchor),
                                     countdownTimer.centerXAnchor.constraint(equalTo: centerXAnchor),
                                     countdownTimer.heightAnchor.constraint(equalToConstant: 300),
                                     countdownTimer.widthAnchor.constraint(equalToConstant: 300)])

    }
}`

**Comment by tsanjoto** [comment]
try putting `countdownView.countdownTimer.start(beginingValue: 5, interval: 1)`
on viewDidAppear instead of viewDidLoad seems like the contraint needs to update first
