### ISSUE TITLE
Label in minutes

### ISSUE THREAD

**Issue by gomitaana** [rsrbk/SRCountdownTimer#8]
It's posible to have the label in minutes?

**Comment by gurhankodalak** [comment]
You can write your own method in `SRCountdownTimer` class or change the existing method called `getMinutesAndSeconds` as returns just minutes.

**Comment by rsrbk** [comment]
Do you want to have only minutes or minutes & seconds?

**Comment by rsrbk** [comment]
Closed due to inactivity.
